name: phone_state_example
description: "Demonstrates how to use the phone_state plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  phone_state:
    path: ../
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
