name: phone_state
description: This plugin allows you to know quickly and easily if your Android or iOS device is receiving a call and to know the status of the call.
version: 3.0.1
homepage: https://github.com/andreamainella98/phone_state

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: it.mainella.phone_state
        pluginClass: PhoneStatePlugin
      ios:
        pluginClass: PhoneStatePlugin